# Generated by Django 5.2.8 on 2025-11-30 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postlike',
            name='unique_post_like',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='user',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'author'), name='unique_post_like'),
        ),
    ]
